### ISSUE TITLE
Build time error

### ISSUE THREAD

**Issue by bahacan19** [chemouna/Decor#2]
No resource identifier found for attribute 'decorAnimate'  in package 'com.exaple.bla' on build time error

**Comment by chemouna** [comment]
Yes , its a typo in readme : the attribute name is decorAnimateSearch, README fixed.

**Comment by bahacan19** [comment]
http://i.imgur.com/sL1pJ4Y.png
still error on some attributes

**Comment by chemouna** [comment]
@bahacan19 seems to be an error in Android Studio 1.3 Preview 1, i was having the same problem i updating to A.S 1.3 Preview 2 fixed it for me (  http://tools.android.com/recent/androidstudio13preview2available, from canary channel).
Let me know if it works..

**Comment by chemouna** [comment]
ah ok, that's a lint error complaining that we are using an app prefix on a framework widget despite it being correct (See https://code.google.com/p/android/issues/detail?id=65176).
to get rid of it add tools:ignore="MissingPrefix" to either the view itself or your RelativeLayout container  (and xmlns:tools="http://schemas.android.com/tools" namespace) .
Samples and readme updated to mention this.
