### ISSUE TITLE
Add decor to views at runtime 

### ISSUE THREAD

**Issue by chemouna** [chemouna/Decor#3]
Allow applying a decorator to a view at runtime, something like : 
TextView textView = new TextView(context); 
Decorator.applyDecor(textView, new AutofitDecorator(sizeToFit));

**Comment by netputer** [comment]
Is it possible to create new view without explicit call `applyDecor`?

**Comment by chemouna** [comment]
applyDecor doesn't exist yet but in each decorator there's an apply method which is called implicitly when you put the custom attribute in your view xml definition (see here https://github.com/chemouna/Decor/blob/master/decor/src/main/java/com/mounacheikhna/decor/DecorFactory.java )

**Comment by netputer** [comment]
Yeah that would be called when layout inflating but not creating view at runtime.
